name: rust release action
on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v7
      - name: release rust project
        uses: lxl66566/rust-simple-release@main
        with:
          targets: |
            aarch64-pc-windows-msvc
            x86_64-pc-windows-msvc
          features: bin
